// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsClcOTzF8wg6Zfv2D7PwaDRYz8cd3zqk',
    appId: '1:86302124785:web:64b8adf3c5c279eab65750',
    messagingSenderId: '86302124785',
    projectId: 'rentvehicle-dee5d',
    authDomain: 'rentvehicle-dee5d.firebaseapp.com',
    storageBucket: 'rentvehicle-dee5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU8ZLF8pnxSRJR_WdwTyw1tCEvKwTm5mE',
    appId: '1:86302124785:android:b03cae8ba830beefb65750',
    messagingSenderId: '86302124785',
    projectId: 'rentvehicle-dee5d',
    storageBucket: 'rentvehicle-dee5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Y4KsgdAuSe-Yj3_jix_jOyKCUxuhNqg',
    appId: '1:86302124785:ios:9efb9642e5e93cecb65750',
    messagingSenderId: '86302124785',
    projectId: 'rentvehicle-dee5d',
    storageBucket: 'rentvehicle-dee5d.firebasestorage.app',
    iosBundleId: 'com.example.rentVehicle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Y4KsgdAuSe-Yj3_jix_jOyKCUxuhNqg',
    appId: '1:86302124785:ios:9efb9642e5e93cecb65750',
    messagingSenderId: '86302124785',
    projectId: 'rentvehicle-dee5d',
    storageBucket: 'rentvehicle-dee5d.firebasestorage.app',
    iosBundleId: 'com.example.rentVehicle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsClcOTzF8wg6Zfv2D7PwaDRYz8cd3zqk',
    appId: '1:86302124785:web:e5f420b99bc67e3ab65750',
    messagingSenderId: '86302124785',
    projectId: 'rentvehicle-dee5d',
    authDomain: 'rentvehicle-dee5d.firebaseapp.com',
    storageBucket: 'rentvehicle-dee5d.firebasestorage.app',
  );
}
